version: '3'
services:
  node:
    build: ./node
    image: nodejs-express
    container_name: express
    volumes:
        - ./node/app:/app
    tty: true
    ports:
        - "8080:3000"
    networks:
        - default
        - shared-network
networks:
    shared-network:
        external: true
        